[service.mvt]
viewer = true

[grid.user]
width = 256
height = 256
extent = { minx = -285401.920, miny = 22598.080, maxx = 595401.920, maxy = 903401.920 }
srid = 28992
units = "m"
resolutions = [3440.640, 1720.320, 860.160, 430.080, 215.040, 107.520, 53.760, 26.880, 13.440, 6.720, 3.360, 1.680, 0.840, 0.420, 0.210, 0.105]
origin = "TopLeft"

[[tileset]]
name = "bgt"
minzoom=0
maxzoom=16
srid = 28992
extent = { minx = -0.515879656010476, miny = 48.0405185807145, maxx = 12.4317273493964, maxy = 55.913622264495 }

[[datasource]]
name = "wegdeel"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "wegdeel_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="wegdeel"
fid_field = "id"
geometry_field = "geom"
geometry_type = "POLYGON"
srid = 28992
datasource="wegdeel"

[[datasource]]
name = "wegdeel_kruinlijn"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "wegdeel_kruinlijn_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="wegdeel_kruinlijn"
fid_field = "id"
geometry_field = "geom"
geometry_type = "LINESTRING"
srid = 28992
datasource="wegdeel_kruinlijn"

[[datasource]]
name = "ondersteunendwegdeel"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "ondersteunendwegdeel_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="ondersteunendwegdeel"
fid_field = "id"
geometry_field = "geom"
geometry_type = "POLYGON"
srid = 28992
datasource="ondersteunendwegdeel"

[[datasource]]
name = "ondersteunendwegdeel_kruinlijn"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "ondersteunendwegdeel_kruinlijn_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="ondersteunendwegdeel_kruinlijn"
fid_field = "id"
geometry_field = "geom"
geometry_type = "LINESTRING"
srid = 28992
datasource="ondersteunendwegdeel_kruinlijn"

[[datasource]]
name = "spoor"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "spoor_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="spoor"
fid_field = "id"
geometry_field = "geom"
geometry_type = "LINESTRING"
srid = 28992
datasource="spoor"

[[datasource]]
name = "onbegroeidterreindeel"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "onbegroeidterreindeel_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="onbegroeidterreindeel"
fid_field = "id"
geometry_field = "geom"
geometry_type = "POLYGON"
srid = 28992
datasource="onbegroeidterreindeel"

[[datasource]]
name = "onbegroeidterreindeel_kruinlijn"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "onbegroeidterreindeel_kruinlijn_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="onbegroeidterreindeel_kruinlijn"
fid_field = "id"
geometry_field = "geom"
geometry_type = "LINESTRING"
srid = 28992
datasource="onbegroeidterreindeel_kruinlijn"

[[datasource]]
name = "begroeidterreindeel"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "begroeidterreindeel_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="begroeidterreindeel"
fid_field = "id"
geometry_field = "geom"
geometry_type = "POLYGON"
srid = 28992
datasource="begroeidterreindeel"

[[datasource]]
name = "begroeidterreindeel_kruinlijn"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "begroeidterreindeel_kruinlijn_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="begroeidterreindeel_kruinlijn"
fid_field = "id"
geometry_field = "geom"
geometry_type = "LINESTRING"
srid = 28992
datasource="begroeidterreindeel_kruinlijn"

[[datasource]]
name = "waterdeel"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "waterdeel_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="waterdeel"
fid_field = "id"
geometry_field = "geom"
geometry_type = "POLYGON"
srid = 28992
datasource="waterdeel"

[[datasource]]
name = "ondersteunendwaterdeel"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "ondersteunendwaterdeel_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="ondersteunendwaterdeel"
fid_field = "id"
geometry_field = "geom"
geometry_type = "POLYGON"
srid = 28992
datasource="ondersteunendwaterdeel"

[[datasource]]
name = "pand"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "pand_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="pand"
fid_field = "id"
geometry_field = "geom"
geometry_type = "POLYGON"
srid = 28992
datasource="pand"

[[datasource]]
name = "pand_nummeraanduiding"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "pand_nummeraanduiding_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="pand_nummeraanduiding"
fid_field = "id"
geometry_field = "geom"
geometry_type = "POINT"
srid = 28992
datasource="pand_nummeraanduiding"

[[datasource]]
name = "overigbouwwerk"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "overigbouwwerk_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="overigbouwwerk"
fid_field = "id"
geometry_field = "geom"
geometry_type = "POLYGON"
srid = 28992
datasource="overigbouwwerk"

[[datasource]]
name = "overbruggingsdeel"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "overbruggingsdeel_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="overbruggingsdeel"
fid_field = "id"
geometry_field = "geom"
geometry_type = "POLYGON"
srid = 28992
datasource="overbruggingsdeel"

[[datasource]]
name = "tunneldeel"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "tunneldeel_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="tunneldeel"
fid_field = "id"
geometry_field = "geom"
geometry_type = "POLYGON"
srid = 28992
datasource="tunneldeel"

[[datasource]]
name = "kunstwerkdeel"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "kunstwerkdeel_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="kunstwerkdeel"
fid_field = "id"
geometry_field = "geom"
geometry_type = "POLYGON"
srid = 28992
datasource="kunstwerkdeel"

[[datasource]]
name = "scheiding"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "scheiding_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="scheiding"
fid_field = "id"
geometry_field = "geom"
geometry_type = "POLYGON"
srid = 28992
datasource="scheiding"

[[datasource]]
name = "overigescheiding"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "overigescheiding_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="overigescheiding"
fid_field = "id"
geometry_field = "geom"
geometry_type = "LINESTRING"
srid = 28992
datasource="overigescheiding"

[[datasource]]
name = "functioneelgebied"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "functioneelgebied_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="functioneelgebied"
fid_field = "id"
geometry_field = "geom"
geometry_type = "POLYGON"
srid = 28992
datasource="functioneelgebied"

[[datasource]]
name = "openbareruimtelabel"
path = "/var/data/in/bgt.gpkg"
[[tileset.layer]]
name = "openbareruimtelabel_{{env.PORT}}"
minzoom=0
maxzoom=16
table_name="openbareruimtelabel"
fid_field = "id"
geometry_field = "geom"
geometry_type = "POINT"
srid = 28992
datasource="openbareruimtelabel"

[webserver]
bind = "0.0.0.0"
port = {{env.PORT}}
threads = {{env.THREAD_COUNT}}
